import { ROLES } from './roles'

export const PERMISSIONS = {
  ADMIN_DASHBOARD_VIEW: 'admin.dashboard.view',
  ADMIN_STORES_MANAGE: 'admin.stores.manage',
  ADMIN_PRODUCTS_MANAGE: 'admin.products.manage',
  ADMIN_CATEGORIES_MANAGE: 'admin.categories.manage',
  ADMIN_COUPONS_MANAGE: 'admin.coupons.manage',
  ADMIN_CUSTOMERS_VIEW: 'admin.customers.view',
  ADMIN_USERS_MANAGE: 'admin.users.manage',
  ADMIN_SETTINGS_MANAGE: 'admin.settings.manage',
  ADMIN_PAYOUTS_MANAGE: 'admin.payouts.manage',

  SELLER_DASHBOARD_VIEW: 'seller.dashboard.view',
  SELLER_STORE_MANAGE: 'seller.store.manage',
  SELLER_PRODUCTS_MANAGE: 'seller.products.manage',
  SELLER_COUPONS_MANAGE: 'seller.coupons.manage',
  SELLER_CUSTOMERS_VIEW: 'seller.customers.view',
  SELLER_ORDERS_VIEW: 'seller.orders.view',
  SELLER_DESIGN_MANAGE: 'seller.design.manage',
  SELLER_PAYOUTS_VIEW: 'seller.payouts.view',

  CUSTOMER_CART_MANAGE: 'customer.cart.manage',
  CUSTOMER_ORDERS_VIEW: 'customer.orders.view',
}

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN.value]: [
    PERMISSIONS.ADMIN_DASHBOARD_VIEW,
    PERMISSIONS.ADMIN_STORES_MANAGE,
    PERMISSIONS.ADMIN_PRODUCTS_MANAGE,
    PERMISSIONS.ADMIN_CATEGORIES_MANAGE,
    PERMISSIONS.ADMIN_COUPONS_MANAGE,
    PERMISSIONS.ADMIN_CUSTOMERS_VIEW,
    PERMISSIONS.ADMIN_USERS_MANAGE,
    PERMISSIONS.ADMIN_SETTINGS_MANAGE,
    PERMISSIONS.ADMIN_PAYOUTS_MANAGE,
  ],
  [ROLES.SELLER.value]: [
    PERMISSIONS.SELLER_DASHBOARD_VIEW,
    PERMISSIONS.SELLER_STORE_MANAGE,
    PERMISSIONS.SELLER_PRODUCTS_MANAGE,
    PERMISSIONS.SELLER_COUPONS_MANAGE,
    PERMISSIONS.SELLER_CUSTOMERS_VIEW,
    PERMISSIONS.SELLER_ORDERS_VIEW,
    PERMISSIONS.SELLER_DESIGN_MANAGE,
    PERMISSIONS.SELLER_PAYOUTS_VIEW,
  ],
  [ROLES.CUSTOMER.value]: [PERMISSIONS.CUSTOMER_CART_MANAGE, PERMISSIONS.CUSTOMER_ORDERS_VIEW],
}
